CREATE INDEX IDX_COMPRA_FECHA_RUBRO_TARJETA ON COMPRA(FECHA_COMPRA, RUBRO, NRO_TARJETA);

WITH COMPRAS_ULT_MES AS (
    SELECT
        C.NRO_TARJETA,
        C.RUBRO,
        C.MONTO
    FROM COMPRA C
    WHERE C.FECHA_COMPRA >= ADD_MONTHS(TRUNC(SYSDATE), -1)
),
PERSONAS_VALIDAS AS (
    SELECT
        T.ID_TITULAR
    FROM COMPRAS_ULT_MES C
    JOIN TARJETA T
        ON T.NRO_TARJETA = C.NRO_TARJETA
    WHERE C.RUBRO IN ('FARMACIA', 'SUPERMERCADOS')
    GROUP BY T.ID_TITULAR
    HAVING SUM(C.MONTO) >= 5000
)
SELECT
    T.NRO_TARJETA
FROM TARJETA T
JOIN PERSONAS_VALIDAS PV
    ON PV.ID_TITULAR = T.ID_TITULAR
WHERE NOT EXISTS (
    SELECT 1
    FROM COMPRAS_ULT_MES C
    WHERE C.NRO_TARJETA = T.NRO_TARJETA
);